const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Follow,
		C3.Plugins.Touch,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{direcao: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{player: 0},
	{Teclado: 0},
	{grama: 0},
	{plantas: 0},
	{objetos: 0},
	{Sólido: 0},
	{solido: 0},
	{aberto: 0},
	{bau: 0},
	{moeda: 0},
	{exibe_moeda: 0},
	{Seguir: 0},
	{inimigo: 0},
	{exibe_inimigo: 0},
	{btn_cima: 0},
	{btn_direita: 0},
	{btn_baixo: 0},
	{btn_esquerda: 0},
	{Toque: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	grama: class extends self.ITilemapInstance {},
	plantas: class extends self.ITilemapInstance {},
	objetos: class extends self.ITilemapInstance {},
	solido: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	moeda: class extends self.ISpriteInstance {},
	exibe_moeda: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	exibe_inimigo: class extends self.ISpriteInstance {},
	btn_cima: class extends self.ISpriteInstance {},
	btn_direita: class extends self.ISpriteInstance {},
	btn_baixo: class extends self.ISpriteInstance {},
	btn_esquerda: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {}
}